import type { Metadata } from 'next';
import { ScrollToTop } from '@/components/ScrollToTop';

export const metadata: Metadata = {
  title: 'Terms of Service — NiraNexus',
  description: 'Terms governing use of NiraNexus deliberative AI infrastructure services.',
};

export default function TermsPage() {
  return (
    <main style={{ backgroundColor: '#05070f', color: '#cbd5e1', minHeight: '100vh', fontFamily: 'var(--font-body)', padding: '4rem 2rem', maxWidth: 720, margin: '0 auto', lineHeight: 1.7 }}>
      <p style={{ fontFamily: 'var(--font-mono)', fontSize: '0.7rem', marginBottom: '2rem' }}>
        <a href="/" style={{ color: '#00ebd4', textDecoration: 'none' }}>&larr; NiraNexus home</a>
      </p>
      <h1 style={{ fontFamily: 'var(--font-display)', fontSize: '2rem', color: '#ffffff', marginBottom: '0.5rem' }}>Terms of Service</h1>
      <p style={{ color: '#94a3b8', fontSize: '0.85rem', marginBottom: '2.5rem' }}>Effective date: 1 July 2026</p>

      <Section heading="1. Acceptance of Terms">
        By accessing or using NiraNexus services, including the Model Council at model-council.niranexus.com, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
      </Section>

      <Section heading="2. Service Description">
        NiraNexus provides deliberative AI infrastructure. The Model Council is a multi-model deliberation engine where frontier language models debate propositions, cross-examine each other, and synthesize findings under a single orchestration layer.
        <br /><br />
        <strong>Advisory nature:</strong> All model outputs — including synthesis verdicts, confidence scores, claims, and dissenting opinions — are generated by AI models and are advisory only. They do not constitute professional advice (legal, financial, medical, or otherwise). You are solely responsible for decisions made based on model outputs.
      </Section>

      <Section heading="3. User Obligations">
        You agree not to:
        <List items={[
          'Use the Service for any unlawful purpose or in violation of applicable laws.',
          'Submit prompts containing personally identifiable information of third parties without their consent.',
          'Use the Service to generate content that is harassing, defamatory, or intended to cause harm.',
          'Attempt to circumvent usage limits, quotas, or authentication mechanisms.',
          'Use automated means (scripts, bots, scrapers) to access the Service without prior written permission.',
        ]} />
      </Section>

      <Section heading="4. Intellectual Property">
        <List items={[
          '<strong>Your content:</strong> You retain ownership of the prompts you submit to the Service.',
          '<strong>Our system:</strong> NiraNexus Ltd retains all rights to the orchestration system, model prompts, synthesis methodology, and the underlying infrastructure.',
          '<strong>Model outputs:</strong> AI-generated responses are produced by third-party models. Ownership of model outputs is determined by each model provider\'s terms.',
        ]} />
      </Section>

      <Section heading="5. No Warranty">
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranty of any kind, express or implied. We do not warrant that the Service will be uninterrupted, timely, error-free, or that model outputs will be accurate or complete.
      </Section>

      <Section heading="6. Limitation of Liability">
        To the maximum extent permitted by law, NiraNexus Ltd shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.
        <br /><br />
        Our total liability for any claim arising from these Terms or your use of the Service is limited to the greater of: (a) the fees you paid to NiraNexus Ltd in the twelve months preceding the claim, or (b) one hundred pounds sterling (GBP 100).
      </Section>

      <Section heading="7. Payments and Refunds">
        <strong>No refunds on provisioned capacity.</strong> When you purchase debate capacity, the capacity is provisioned immediately. Because deliberation is consumed at the moment a debate runs — models are invoked, tokens are processed, and infrastructure costs are incurred — all purchases are final and non-refundable.
        <br /><br />
        <strong>Chargebacks.</strong> If you initiate a chargeback, payment dispute, or reversal through your bank or card provider, your account will be suspended immediately pending resolution. Any remaining debate capacity at the time of the chargeback is forfeited and will not be restored, regardless of the outcome. You remain liable for any fees, costs, or penalties incurred by NiraNexus Ltd as a result of the chargeback, including reasonable administrative costs.
        <br /><br />
        <strong>Service credits.</strong> At our sole discretion, we may issue service credits in cases of verified Service unavailability or material failure. Service credits extend debate capacity only — they are not redeemable for cash, refund, or transfer.
      </Section>

      <Section heading="8. Termination">
        We reserve the right to suspend or terminate your access to the Service at our sole discretion, without prior notice, for conduct that we believe violates these Terms or is otherwise harmful to the Service, other users, or third parties.
      </Section>

      <Section heading="9. Governing Law">
        These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.
      </Section>

      <ScrollToTop />
    </main>
  );
}

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: '2rem' }}>
      <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '1.2rem', color: '#ffffff', marginTop: '2rem', marginBottom: '0.75rem' }}>{heading}</h2>
      {children}
    </section>
  );
}

function List({ items }: { items: string[] }) {
  return (
    <ul style={{ paddingLeft: '1.25rem', marginTop: '0.5rem', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
      {items.map((item, i) => (
        <li key={i} style={{ fontSize: '0.9rem', lineHeight: 1.7 }} dangerouslySetInnerHTML={{ __html: item }} />
      ))}
    </ul>
  );
}
